/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.admincampos.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import poo.admincampos.Campo;
import poo.admincampos.EstadoCampo;
import poo.admincampos.Lote;
import poo.admincampos.TipoSuelo;
import poo.admincampos.ui.TablaLotesModel;
import poo.admincampos.controller.AdministradorCampos;

/**
 *
 * @author facundo
 */
public class PantallaRegistracionCampo extends javax.swing.JFrame {
    
    AdministradorCampos administradorCampos;
    
    List<TipoSuelo> tipoSuelos;
    List<Lote> lotes;
    
    TablaLotesModel tablaLotesModel;
    Campo campo;
    
    /**
     * Creates new form PantallaRegistracionCampo
     */
    public PantallaRegistracionCampo(AdministradorCampos administradorCampos) {
        
        this.administradorCampos = administradorCampos;
        
        //tipoSuelos = new ArrayList<TipoSuelo>();
        //tipoSuelos.add(new TipoSuelo("Tipo1"));
        tipoSuelos = administradorCampos.obtenerTipoSuelos();
        
        
        //cargar lotes prueba
        lotes = new ArrayList<Lote>();
        //EstadoCampo estadocampo = new EstadoCampo("creado");
        //Campo campo = new Campo("campo1", estadocampo);
        //TipoSuelo tiposuelo = new TipoSuelo("Tierra negra");
        //Lote lote = new Lote(1,10, tiposuelo, campo);
        //lotes.add(lote);
        
        
        this.tablaLotesModel = new TablaLotesModel(this.lotes);
        
        
        EstadoCampo estadocampo = administradorCampos.getEstadoCreado();
        campo = new Campo("", estadocampo);
        

        initComponents();
        
        lblWarningCampoNombre.setVisible(false);
        lblWarningLoteNro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCampo = new javax.swing.JTextField();
        txtSuperficieCampo = new javax.swing.JTextField();
        lblWarningCampoNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNroLote = new javax.swing.JTextField();
        txtSuperficieLote = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbTipoSuelo = new javax.swing.JComboBox<>();
        lblWarningLoteNro = new javax.swing.JLabel();
        btnAgregarLote = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnRegistrarCampo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLotes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Superficie:");

        lblWarningCampoNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningCampoNombre.setText("Este nombre ya está en uso");
        lblWarningCampoNombre.setName(""); // NOI18N

        jLabel4.setText("Usuario: Admin");

        jLabel5.setText("ha.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Lotes");

        jLabel7.setText("Tenga en cuenta que debe ingresar al menos 1 lote");

        jLabel8.setText("Nro.:");

        jLabel9.setText("Superficie:");

        jLabel10.setText("Tipo de Suelo:");

        jLabel11.setText("ha.");

        cbTipoSuelo.setModel(new DefaultComboBoxModel(tipoSuelos.toArray()));

        lblWarningLoteNro.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningLoteNro.setText("Este número de lote ya está en uso");

        btnAgregarLote.setText("Agregar Lote");
        btnAgregarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLoteActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");

        jButton4.setText("Quitar");

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnRegistrarCampo.setText("Registrar Campo");
        btnRegistrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCampoActionPerformed(evt);
            }
        });

        tableLotes.setModel(this.tablaLotesModel);
        jScrollPane1.setViewportView(tableLotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNroLote)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel11))
                                                .addComponent(cbTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(lblWarningLoteNro)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnAgregarLote))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWarningCampoNombre)
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(208, 208, 208))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton4)
                                        .addGap(328, 328, 328))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnRegistrarCampo)
                                        .addGap(268, 268, 268))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWarningCampoNombre)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblWarningLoteNro)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarLote)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCampo)
                    .addComponent(jButton5))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAgregarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLoteActionPerformed
        // TODO add your handling code here:
        
        Integer nroLote = Integer.valueOf(txtNroLote.getText());
        
        if(buscarLote(nroLote)!=null) {
            lblWarningLoteNro.setVisible(true);
            return;
        } else {
            lblWarningLoteNro.setVisible(false);
        }
        
        Integer superficieLote = Integer.valueOf(txtSuperficieLote.getText());
        TipoSuelo tipoSuelo = (TipoSuelo)(cbTipoSuelo.getSelectedItem());
        
        Lote lote = new Lote(nroLote,superficieLote, tipoSuelo, campo);
        this.lotes.add(lote);
        
        tablaLotesModel.setLotes(this.lotes);
        tablaLotesModel.fireTableDataChanged();
        
        txtNroLote.setText("");
        txtSuperficieLote.setText("");
    }//GEN-LAST:event_btnAgregarLoteActionPerformed

    
    Lote buscarLote(Integer numeroLote) {
        for(Lote lote : this.lotes) {
            if(lote.getNumeroLote().equals(numeroLote)) {
                return lote;
            }
        }
        return null;
    }
    
    private void btnRegistrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCampoActionPerformed
        // TODO add your handling code here:
        
        String nombreCampo = txtNombreCampo.getText();
        Integer superficieCampo = Integer.valueOf(txtSuperficieCampo.getText());

        if(administradorCampos.buscarCampo(nombreCampo)!=null) {
            lblWarningCampoNombre.setVisible(true);
            return;
        } else {
            lblWarningCampoNombre.setVisible(false);
        }
        
        Integer sumSuperficieLotes = 0;
        for(Lote lote: lotes){
            sumSuperficieLotes += lote.getSuperficie();
        }
        
        if(sumSuperficieLotes!=superficieCampo){
            JOptionPane.showMessageDialog(null, "La superficie total de los lotes no coincide con la superficie del campo");
            return;
        }
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Confirma el registro del campo?","Warning",dialogButton);
        if(dialogResult != JOptionPane.YES_OPTION){
          return;
        }
        
        // setear nombre de campo y referencia a los lotes
        campo.setNombre(nombreCampo);
        campo.setLotes(lotes);
        
        // guardar campo y lotes
        administradorCampos.registrarCampo(lotes);
        
        // mostrar pantalla del campo creado
        
        
        new PantallaCampoCreado(lotes).setVisible(true);
        
        // limpiar pantalla y reestablecer estado
        //resetForm();
    }//GEN-LAST:event_btnRegistrarCampoActionPerformed

    public void resetForm(){
        txtNombreCampo.setText("");
        txtSuperficieCampo.setText("");
        txtNroLote.setText("");
        txtSuperficieLote.setText("");
        
        EstadoCampo estadocampo = administradorCampos.getEstadoCreado();
        campo = new Campo("", estadocampo);
        
        lotes.clear();
        lotes = new ArrayList<Lote>();
        tablaLotesModel.setLotes(this.lotes);
        tablaLotesModel.fireTableDataChanged();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistracionCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistracionCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistracionCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistracionCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistracionCampo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLote;
    private javax.swing.JButton btnRegistrarCampo;
    private javax.swing.JComboBox<String> cbTipoSuelo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWarningCampoNombre;
    private javax.swing.JLabel lblWarningLoteNro;
    private javax.swing.JTable tableLotes;
    private javax.swing.JTextField txtNombreCampo;
    private javax.swing.JTextField txtNroLote;
    private javax.swing.JTextField txtSuperficieCampo;
    private javax.swing.JTextField txtSuperficieLote;
    // End of variables declaration//GEN-END:variables
}
